spring:
  application:
    name: transfer-service
  cloud:
    stream:
      schema-registry-client:
        endpoint: http://localhost:8081
      kafka:
        streams:
          binder:
            configuration:
              application:
                id: fraud-service
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              schema:
                registry:
                  url: http://localhost:8081
              value:
                subject:
                  name:
                    strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
      bindings:
        input:
          destination: test-postgresql-jdbc-movement
          consumer:
            useNativeDecoding: true
        outputOk:
          destination: account
          producer:
            useNativeEncoding: true
        outputKo:
          destination: fraudulent-transfer
          producer:
            useNativeEncoding: true

server:
  port: 8086

logging:
  level:
    org.springframework.kafka.config: debug
